################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../gecko_sdk_4.4.1/platform/emlib/src/em_burtc.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_cmu.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_core.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_emu.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_eusart.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_gpio.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_i2c.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_ldma.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_msc.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_prs.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_system.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_timer.c \
../gecko_sdk_4.4.1/platform/emlib/src/em_usart.c 

OBJS += \
./gecko_sdk_4.4.1/platform/emlib/src/em_burtc.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_core.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_emu.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_eusart.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_i2c.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_ldma.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_msc.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_prs.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_system.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_timer.o \
./gecko_sdk_4.4.1/platform/emlib/src/em_usart.o 

C_DEPS += \
./gecko_sdk_4.4.1/platform/emlib/src/em_burtc.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_core.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_emu.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_eusart.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_i2c.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_ldma.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_msc.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_prs.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_system.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_timer.d \
./gecko_sdk_4.4.1/platform/emlib/src/em_usart.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.4.1/platform/emlib/src/em_burtc.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_burtc.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_burtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_cmu.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_cmu.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_core.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_core.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_emu.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_emu.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_eusart.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_eusart.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_eusart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_gpio.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_gpio.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_i2c.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_i2c.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_i2c.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_ldma.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_ldma.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_msc.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_msc.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_prs.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_prs.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_prs.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_system.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_system.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_timer.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_timer.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.1/platform/emlib/src/em_usart.o: ../gecko_sdk_4.4.1/platform/emlib/src/em_usart.c gecko_sdk_4.4.1/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD4186C"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\config" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\autogen" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\Device\SiliconLabs\EFR32MG24\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\board\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\CMSIS\Core\Include" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\configuration_over_swo\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\debug\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\device_init\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\dmadrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emdrv\common\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\emlib\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\i2cspm\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\iostream\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\driver\leddrv\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\hardware\driver\mx25_flash_shutdown\inc\sl_mx25_flash_shutdown_usart" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\peripheral\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\common\toolchain\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\system\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\sleeptimer\inc" -I"C:\Users\Halcyon\Desktop\CUSP24\ECEN5833\LPEDT_Software\gecko_sdk_4.4.1\platform\service\udelay\inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.1/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


